"""Add User model and game_user association table

Revision ID: 738eee2c80c6
Revises: e5a89a5950f9
Create Date: 2024-07-22 05:17:37.386357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738eee2c80c6'
down_revision = 'e5a89a5950f9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
